# Generated by Django 5.0.6 on 2024-05-31 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('arrival', 'Прилет'), ('departure', 'Вылет'), ('transit', 'Транзит')], max_length=100)),
                ('price_one_passenger', models.CharField()),
                ('price_others_passengers', models.CharField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='airport.airport')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_price', to='main_app.service')),
            ],
        ),
    ]
