# Generated by Django 5.0.6 on 2024-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='price_one_passenger',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price_others_passengers',
            field=models.CharField(max_length=50),
        ),
    ]
