# Generated by Django 5.0.6 on 2024-06-13 11:24

import main_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[main_app.utils.valid_phone_number]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(validators=[main_app.utils.age_type]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[main_app.utils.valid_phone_number]),
        ),
    ]
