# Generated by Django 5.0.6 on 2024-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='booking_history',
        ),
        migrations.AddField(
            model_name='passenger',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
