# Generated by Django 5.0.6 on 2024-06-05 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_account_booking_history_passenger_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='passenger',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
