# Generated by Django 5.0.6 on 2024-05-31 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=100)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('booking_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен')], max_length=100)),
                ('passenger_age', models.CharField(choices=[('infant', 'Ребенок (0-2 лет)'), ('child', 'Ребенок (2-12 лет)'), ('adult', 'Взрослый')], max_length=100)),
                ('passenger_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_booking', to='airport.airport')),
                ('arrival_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_service', to='main_app.serviceprice')),
                ('arrival_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_booking', to='airport.terminal')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_booking', to='airport.airport')),
                ('departure_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_service', to='main_app.serviceprice')),
                ('departure_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_booking', to='airport.terminal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
