# Generated by Django 5.0.6 on 2024-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен')], default='unpaid', max_length=100),
        ),
    ]
