# Generated by Django 5.0.6 on 2024-06-10 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_terminal',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_booking', to='airport.terminal'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_terminal',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='departure_booking', to='airport.terminal'),
        ),
    ]
