# Generated by Django 5.0.6 on 2024-06-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_passenger_and_more'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ManyToManyField(through='booking.PassengerBooking', to='main_app.passenger'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_service', to='main_app.serviceprice'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_service', to='main_app.serviceprice'),
        ),
        migrations.AlterField(
            model_name='passengerbooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_booking', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='passengerbooking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_booking', to='main_app.passenger'),
        ),
    ]
