# Generated by Django 5.0.6 on 2024-06-12 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_passenger_alter_booking_arrival_service_and_more'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transit_service', to='main_app.serviceprice'),
        ),
    ]
