# Generated by Django 5.0.6 on 2024-06-13 11:24

import django.utils.timezone
import main_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_transit_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerbooking',
            name='date_created',
        ),
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[main_app.utils.valid_phone_number]),
        ),
    ]
